---
- name: Build and Redeploy Docker Containers
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    docker_password: "test"
    container_count: 10
    container_count_int: "{{ container_count | int }}"
    base_ssh_port: 22220                # first container will use 22221
    inventory_yaml: "{{ playbook_dir }}/machines.yml"
  tasks:
    - name: Build custom Alpine image (if Dockerfile changed)
      community.docker.docker_image:
        name: custom-alpine-ansible
        build:
          path: "."
          pull: yes
          args:
            PASSWORD: "{{ docker_password }}"
        source: build
        force_source: true

    - name: Run new containers
      community.docker.docker_container:
        name: "alpine-container-{{ item }}"
        image: custom-alpine-ansible
        state: started
        detach: yes
        ports:
          - "{{ (base_ssh_port | int) + (item | int) }}:22"
        recreate: yes
      loop: "{{ range(1, container_count_int + 1) | list }}"

    - name: Wait briefly before scanning for SSH keys
      ansible.builtin.command: sleep 2
      changed_when: false

    - name: Add new SSH host keys to known_hosts
      ansible.builtin.shell: >
        ssh-keyscan -p {{ (base_ssh_port | int) + (item | int) }} localhost >> ~/.ssh/known_hosts 2>/dev/null
      loop: "{{ range(1, container_count_int + 1) | list }}"
      changed_when: false
      retries: 3
      delay: 2
      until: true

    - name: Generate inventory file in YAML
      ansible.builtin.copy:
        dest: "{{ inventory_yaml }}"
        content: |
          machines:
          {% for i in range(1, container_count_int + 1) %}
            - name: alpine-container-{{ i }}
              host: localhost
              port: {{ (base_ssh_port | int) + i }}
              user: root
              password: {{ docker_password }}
          {% endfor %}
