---
- name: Create user in Alpine Docker containers
  hosts: all
  become: yes
  vars:
    username: "test"
    password: "test"  # Hardcoded password
  tasks:
    - name: Install sudo and bash (if needed)
      ansible.builtin.apk:
        name:
          - sudo
          - bash
        state: present

    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/sh  # Alpine uses /bin/sh by default
        groups: wheel    # Alpine uses 'wheel' group for sudo

    - name: Allow passwordless sudo for the user
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
