---
- name: Create users in Docker containers
  hosts: all
  become: yes
  vars:
    username: "test"
    password: "test"
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Set password for user
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        line: "{{ username }} ALL=(ALL) NOPASSWD:ALL"
        validate: 'visudo -cf %s'
