---
- name: Install Dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install Ansible
      ansible.builtin.apt:
        name: ansible
        state: present
        update_cache: yes

    - name: Install Docker for AMD64 (x86_64)
      when: ansible_architecture == "x86_64"
      block:
        - name: Add Docker GPG key (AMD64)
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository (AMD64)
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            update_cache: yes

        - name: Install Docker packages (AMD64)
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: yes

    # used by macos since it emulates arm64
    - name: Install Docker for ARM64
      when: ansible_architecture == "aarch64"
      block:
        - name: Add Docker GPG key (ARM64)
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker repository (ARM64)
          ansible.builtin.apt_repository:
            repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            update_cache: yes

        - name: Install Docker packages (ARM64)
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: yes

    - name: Ensure Docker is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Ubuntu image
      community.docker.docker_image:
        name: ubuntu
        source: pull
        tag: latest

    - name: Run 10 Ubuntu containers
      community.docker.docker_container:
        name: "ubuntu-container-{{ item }}"
        image: ubuntu:latest
        state: started
        detach: yes
        command: ["tail", "-f", "/dev/null"]  # Keep container running
      loop: "{{ range(1, 11) | list }}"
