---
- name: Install Dependencies
  hosts: all
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - ansible
          - python3-docker
          - python3-venv
          - curl
          - just
        state: present
        update_cache: yes

    - name: Install Docker for AMD64 (x86_64)
      when: ansible_architecture == "x86_64"
      block:
        - name: Add Docker GPG key (AMD64)
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Add Docker repository (AMD64)
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            update_cache: yes
        - name: Install Docker packages (AMD64)
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: yes

    - name: Install Docker for ARM64
      when: ansible_architecture == "aarch64"
      block:
        - name: Add Docker GPG key (ARM64)
          ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present
        - name: Add Docker repository (ARM64)
          ansible.builtin.apt_repository:
            repo: "deb [arch=arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
            state: present
            update_cache: yes
        - name: Install Docker packages (ARM64)
          ansible.builtin.apt:
            name:
              - docker-ce
              - docker-ce-cli
              - containerd.io
            state: present
            update_cache: yes

    - name: Install Go (Golang)
      block:
        - name: Download Go binary
          ansible.builtin.get_url:
            url: "https://go.dev/dl/go1.20.5.linux-amd64.tar.gz"  # Change version as necessary
            dest: "/tmp/go1.20.5.linux-amd64.tar.gz"

        - name: Extract Go binary
          ansible.builtin.unarchive:
            src: "/tmp/go1.20.5.linux-amd64.tar.gz"
            dest: "/usr/local/"
            remote_src: yes

        - name: Set Go environment variables
          ansible.builtin.linein_file:
            path: "/etc/profile"
            line: 'export PATH=$PATH:/usr/local/go/bin'
            state: present

        - name: Source the profile file to apply changes
          ansible.builtin.shell:
            cmd: source /etc/profile

    - name: Ensure Docker is running and enabled
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes
