Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"
  config.vm.hostname = "VM-ressources"
  config.vm.network "private_network", ip: "192.168.56.20"
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end

  config.ssh.insert_key = true

  # Ansible needs to be installed on the host for this to work
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "setup.yml"
    ansible.verbose = "v"
    ansible.limit = "all"
  end

end
