---
- name: Manage user in Alpine Docker containers
  hosts: all
  become: true
  tasks:
    - name: Create user
      ansible.builtin.user:
        name: "{{ username }}"
        #password: "{{ password | password_hash('sha512') }}"
        password: "{{ hashed_password }}"
        shell: /bin/sh
        groups: wheel
        state: present
      when: user_action == 'create'

    - name: Delete user
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
        remove: yes
      when: user_action == 'delete'
