services:
  db:
    image: mariadb:11
    environment:
      - MARIADB_DATABASE=containers
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=apppass
      - MARIADB_ROOT_PASSWORD=rootpass
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    network_mode: "host"  # demo: API needs SSH to localhost
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppass@127.0.0.1:3306/containers?charset=utf8mb4
      - DB_CONNECT_MAX_RETRIES=120
      - DB_CONNECT_RETRY_SECONDS=1
    depends_on:
      db:
        condition: service_healthy

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    network_mode: "host"  # demo: if it also needs localhost SSH
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppass@127.0.0.1:3306/containers?charset=utf8mb4
      - DB_CONNECT_MAX_RETRIES=120
      - DB_CONNECT_RETRY_SECONDS=1
    depends_on:
      db:
        condition: service_healthy
    # To run once instead of loop:
    # command: ["python", "-m", "scheduler.maintenance", "--once"]

volumes:
  db_data:
