services:
  db:
    image: mariadb:11
    environment:
      - MARIADB_DATABASE=containers
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=apppass
      - MARIADB_ROOT_PASSWORD=rootpass
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab

  api:
    build:
      context: .
      dockerfile: api-go/Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppass@db:3306/containers?charset=utf8mb4
      - LOG_LEVEL=INFO
      - ANSIBLE_FORKS=5
      # Auth config
      - JWT_SECRET=${JWT_SECRET:-change-me-in-prod}
      #- JWT_EXPIRES_MINUTES=60
      - ANSIBLE_HOST_KEY_CHECKING=false
      - ADMIN_DEFAULT_USERNAME=${ADMIN_DEFAULT_USERNAME:-admin}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD:-change-me}
    depends_on:
      db:
        condition: service_healthy
    stop_grace_period: 30s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lab

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppass@db:3306/containers?charset=utf8mb4
      - DB_CONNECT_MAX_RETRIES=120
      - DB_CONNECT_RETRY_SECONDS=1
      - DB_LOCK_TIMEOUT=0
      - ANSIBLE_FORKS=5
      - CLEANUP_BATCH_SIZE=20
    depends_on:
      db:
        condition: service_healthy
    stop_signal: SIGTERM
    stop_grace_period: 90s
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - lab

  reverse-proxy:
    build:
      context: .
      dockerfile: reverse-proxy/Dockerfile
    ports:
      - "443:443"
    environment:
      - DOMAIN=example.com
      - EMAIL=you@example.com
    volumes:
      # Optionally bind-mount Caddyfile for quick edits; image also COPYs it
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - edge
      - lab

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  edge:
    driver: bridge
  lab:
    driver: bridge
