services:
  db:
    image: mariadb:11
    environment:
      - MARIADB_DATABASE=containers
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=apppass
      - MARIADB_ROOT_PASSWORD=rootpass
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - lab

  api:
    build:
      context: .
      dockerfile: api-go/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=containers
      - DB_USER=appuser
      - DB_PASSWORD=apppass

      # Optional DB tuning (defaults shown)
      # - DB_CHARSET=utf8mb4
      # - DB_COLLATION=utf8mb4_unicode_ci
      # - DB_TIMEOUT=5s
      # - DB_READ_TIMEOUT=5s
      # - DB_WRITE_TIMEOUT=5s

      # Auth config
      - JWT_SECRET=${JWT_SECRET:-change-me-in-prod}
      #- JWT_EXPIRES_MINUTES=60 need to reimplement it

      # Default account for the API
      - ADMIN_DEFAULT_USERNAME=${ADMIN_DEFAULT_USERNAME:-admin}
      - ADMIN_DEFAULT_PASSWORD=${ADMIN_DEFAULT_PASSWORD:-change-me}

      # Ansible-related
      - ANSIBLE_FORKS=5
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./secrets:/app/secrets:ro
    networks:
      - lab

  scheduler:
    build:
      context: .
      dockerfile: scheduler-go/Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=containers
      - DB_USER=appuser
      - DB_PASSWORD=apppass
      - ANSIBLE_FORKS=5
      - CLEANUP_BATCH_SIZE=20
      - DB_LOCK_TIMEOUT=0
      # Optional loop tuning (defaults shown)
      # - SCHEDULER_INTERVAL=60
    depends_on:
      db:
        condition: service_healthy
    stop_signal: SIGTERM
    stop_grace_period: 90s
    restart: unless-stopped
    volumes:
      - ./secrets:/app/secrets:rw
    networks:
      - lab

  reverse-proxy:
    image: caddy:2.8-alpine
    ports:
      - "443:443"
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
    depends_on:
      - api
    networks:
      - lab

volumes:
  db_data:

networks:
  lab:
    driver: bridge
