services:
  db:
    image: mariadb:11
    environment:
      - MARIADB_DATABASE=containers
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=apppass
      - MARIADB_ROOT_PASSWORD=rootpass
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    network_mode: "host"
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppass@127.0.0.1:3306/containers?charset=utf8mb4
      - DB_CONNECT_MAX_RETRIES=120
      - DB_CONNECT_RETRY_SECONDS=1
      # Optional log tuning:
      # - GUNICORN_LOGLEVEL=warning
      # - ENABLE_ACCESS_LOG=false
      # - LOG_LEVEL=INFO
    depends_on:
      db:
        condition: service_healthy
    # Give Gunicorn time to drain and exit cleanly
    stop_grace_period: 10s

  scheduler:
    build:
      context: .
      dockerfile: scheduler/Dockerfile
    network_mode: "host"
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppass@127.0.0.1:3306/containers?charset=utf8mb4
      - DB_CONNECT_MAX_RETRIES=120
      - DB_CONNECT_RETRY_SECONDS=1
      # Optional: how long to wait for advisory lock acquisition
      # - DB_LOCK_TIMEOUT=2
    depends_on:
      db:
        condition: service_healthy
    # Allow current playbook to finish or terminate cleanly before SIGKILL
    stop_signal: SIGTERM
    stop_grace_period: 90s

volumes:
  db_data:
