services:
  db:
    image: mariadb:11
    environment:
      - MARIADB_DATABASE=containers
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=apppass
      - MARIADB_ROOT_PASSWORD=rootpass
    ports:
      - "3306:3306"
    healthcheck:
      # --silent exits 0 when server is ready to accept connections
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./
    environment:
      - DATABASE_URL=mysql+pymysql://appuser:apppass@db:3306/containers?charset=utf8mb4
      # Optional: make API keep retrying longer if your DB is slow to initialize
      - DB_CONNECT_MAX_RETRIES=120
      - DB_CONNECT_RETRY_SECONDS=1
      # Optional dev-only fallback if DB never comes up:
      # - DB_FALLBACK_TO_SQLITE=true
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
