name: Build and Push Docker Image on Dispatch

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push custom-alpine-ansible
        uses: docker/build-push-action@v5
        with:
          context: ./provision
          push: true
          tags: ghcr.io/${{ github.repository }}/custom-alpine-ansible:latest
          build-args: |
            PASSWORD=test
